INSERT INTO Users (name, password, role, createdAt, updatedAt)
VALUES ("cs", "123", "Artist", NOW(), NOW()),
       ("thewho", "123", "Artist", NOW(), NOW()), 
       ("rollingstones", "123", "Artist", NOW(), NOW()),
       ("beck", "123","Artist", NOW(), NOW());

INSERT INTO Artists (artistName, genre, instrumentation, numberOfMembers, email, phone, profileImage, website, createdAt, updatedAt, UserId )
            VALUES  ( "Collective Soul",
                      "Rock",
                      "guitars,bass,drums",
                       5,
                      "ColectiveSoul@UTBootCamp.edu",
                      "(555) 555-5555", 
                      "https://image-ticketfly.imgix.net/00/03/02/11/07-og.jpg?w=650&h=650", 
                      "http://www.collectivesoul.com/",
                      NOW(), NOW(), 1 ),

                    ( "The Who",
                      "Classic Rock",
                      "guitar, bass, drums, vocalist",
                       4, 
                      "TheWho@UTBootCamp.edu", 
                      "(555) 555-5555", 
                      "http://www.lovethispic.com/uploaded_images/29493-The-Who-Rock-Band.jpg", 
                      "http://www.thewho.com/",
                       NOW(), NOW(), 2 ),

                    ( "The Rolling Stones", 
                      "Classic Rock", 
                      "guitar, bass, drums, vocalist",
                       4,
                      "TheRollingStones@UTBootCamp.edu", 
                      "(555) 555-5555", 
                      "https://www.billboard.com/files/styles/article_main_image/public/media/the-rolling-stones-portrait-bw-1964-billboard-1548.jpg", 
                      "https://www.rollingstones.com/",
                        NOW(), NOW(), 3 ),

                     ( "Beck", 
                       "Rock",
                       "full set", 
                        5, 
                        "stonesATX@UTBootCamp.edu", 
                        "(555) 555-5555", 
                        "https://media.gettyimages.com/photos/american-musician-beck-headlines-a-benefit-concert-for-and-at-central-picture-id501589579?s=612x612", 
                        "www.beck.com",
                         NOW(), NOW(), 4 );

INSERT INTO Users (name, password, role, createdAt, updatedAt )
VALUES ("hitw", "123", "Venue", NOW(), NOW()),
       ("emos", "123", "Venue", NOW(), NOW()),
       ("antones", "123", "Venue", NOW(), NOW()),
       ("bdr", "123", "Venue", NOW(), NOW()),
       ("litlounge", "123", "Venue", NOW(), NOW()),
       ("bs", "123", "Venue", NOW(), NOW()),
       ("one2one", "123", "Venue", NOW(), NOW());

INSERT INTO Venues (venueName, street_address, city, state, zipcode, phone, email, website, image, createdAt, updatedAt, UserId) 
            VALUES ( "Hole in the Wall",
                     "2538 Guadalupe St.", "Austin", "TX", "78705", "(555) 555-5555", "HoleInTheWall@UTBootCamp.edu",
                     "https://www.holeinthewallaustin.com/",
                     "https://www.holeinthewallaustin.com/fullscreen-page/comp-jc7gdz3r/e388a146-0979-4682-a11d-838d7e421b16/6/%3Fi%3D6%26p%3Dacsro%26s%3Dstyle-ji24vi6q%26rl%3D1",
                      NOW(), NOW(), 5),

                   ( "Emo's",
                     "2015 E Riverside Dr.", "Austin", "TX", "78741", 
                     "(555) 555-5555",
                     "Emos@UTBootCamp.edu",
                     "https://www.emosaustin.com/",
                     "https://static.spacecrafted.com/d0ff1849232e40769aef8fe7be7d853d/i/cffda9680b0848c0ae916497614c8fce/2/GCuCv726gZycFxatknDdac/003_Emo?dpr=2%27s-Resized.jpg",
                     NOW(), NOW(),  6),

                   ( "Antone's Nightclub",
                     "305 E 5th St.", "Austin", "TX", "78701", 
                     "(555) 555-5555", 
                     "Antones@UTBootCamp.edu",
                     "https://www.antonesnightclub.com/",
                     "https://scontent-sea1-1.cdninstagram.com/vp/55dae11e94dc3a565059b30f155b4bc3/5D7665C1/t51.2885-15/e35/56416968_649136208857094_500001289747272358_n.jpg?_nc_ht=scontent-sea1-1.cdninstagram.com",
                     NOW(), NOW(), 7),

                   ( "B.D. Riley's Irish Pub",
                     "204 E 6th St.", "Austin", "TX", "78701", 
                     "(555) 555-5555",
                     "BDRileys@UTBootCamp.edu",
                     "https://bdrileys.com/",
                     "https://bdrileys.com/wp-content/themes/bdrileys/images/homesixthstreet.jpg",
                     NOW(), NOW(), 8),

                   ( "Lit Lounge",
                     "215 East 6th Street", "Austin", "TX", "78701",
                     "(512) 466-2604",
                     "LitLounge@UTBootCamp.edu",
                     "https://litloungeaustin.com/",
                     "https://litloungeaustin.com/images/page2-img1.jpg",
                      NOW(), NOW(), 9),

                     ("Broken Spoke",
                     "3201 S Lamar Blvd", "Austin", "TX", "78704",
                     "(555) 555-5555",
                     "BrokenSpoke@UTBootCamp.edu",
                     "https://www.brokenspokeaustintx.net/",
                     "https://images.unsplash.com/photo-1508252592163-5d3c3c559f36?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80",
                     NOW(), NOW(), 10),

                    ("One-2-One Bar",
                     "1509 S Lamar Blvd", "Austin", "TX", "78704",
                     "(555) 555-5555",
                     "OneToOne@UTBootCamp.edu",
                     "http://www.one2onebar.com/",
                     "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
                      NOW(), NOW(), 11);

INSERT INTO Gigs (gigName, genre, street_address, city, state, zipcode, phone, description, image, date, isBooked, createdAt, updatedAt, VenueId ) 
            VALUES ( "Hole in the Wall",
                    "Rock",
                     "2538 Guadalupe St.", "Austin", "TX", "78705", 
                     "(555) 555-5555", 
                     "Electric Boogaloo",
                     "http://www.one2onebar.com/index_files/stacks-image-55009ff.jpg",
                     "4/26/2019 8:00PM",
                     false, NOW(), NOW(), 1 ),

                    ( "Emo's",
                     "RocknRoll!!",
                     "2015 E Riverside Dr.", "Austin", "TX", "78741", 
                     "(555) 555-5566",
                     "Aquatic Boogaloo",
                     "https://static.spacecrafted.com/d0ff1849232e40769aef8fe7be7d853d/i/c1a873b75fab499d8654dc751d9f5554/2/GCuCv726gZycFxatknDdac/SEVENLIONS-EMOS-11.29.18-11_1920w.jpg",
                     "4/26/2019 8:00PM",
                     false, NOW(), NOW(), 2 ),

                     ( "Lit Lounge",
                       "Smooth Jazz",
                       "215 East 6th Street", "Austin", "TX", "78701",
                       "(512) 466-2604",
                       "Premiere destination for Austin’s elite crowd ",
                       "https://litloungeaustin.com/images/page2-img1.jpg",
                       "Saturday, April 27, 2019, 7:00pm - 10:00pm",
                       false, NOW(), NOW(), 5 ),

                     ("Broken Spoke",
                     "Both kinds - Country AND Western",
                     "3201 S Lamar Blvd", "Austin", "TX", "78704",
                     "(555) 555-5555",
                     "Honky Tonk",
                     "https://images.unsplash.com/photo-1508252592163-5d3c3c559f36?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80",
                     "Saturday Night,  April 27, 2019, 9:00pm - 11:59pm",
                       false, NOW(), NOW(), 6 ),

                     ("One-2-One Bar",
                     "Anything goes!!",
                     "1509 S Lamar Blvd", "Austin", "TX", "78704",
                     "(555) 555-5555",
                     "Rager",
                     "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
                     "Saturday Night, April 27, 2019, 8:00 to 11:00 PM",
                     false, NOW(), NOW(), 7 ),

                    ( "Hole in the Wall",
                     "Home spun ANYTHING!",
                     "2538 Guadalupe St.", "Austin", "TX", "78705", 
                     "(555) 555-5555", 
                     "Electric Boogaloo",
                     "http://www.one2onebar.com/index_files/stacks-image-55009ff.jpg",
                     "Friday Night, April 26, 2019, 8:00 to 11:00",
                     false, NOW(), NOW(), 1 ),

                    ( "Emo's",
                     "GRUNGE!!",
                     "2015 E Riverside Dr.", "Austin", "TX", "78741", 
                     "(555) 555-5566",
                     "The dirtier the better!!",
                     "https://static.spacecrafted.com/d0ff1849232e40769aef8fe7be7d853d/i/c1a873b75fab499d8654dc751d9f5554/2/GCuCv726gZycFxatknDdac/SEVENLIONS-EMOS-11.29.18-11_1920w.jpg",
                     "Saturday Night, April 27, 2019, 8:00 to 11:00 PM",
                     false, NOW(), NOW(), 2 ),

                     ( "Lit Lounge",
                      "Smoooooooooth",
                       "215 East 6th Street", "Austin", "TX", "78701",
                       "(512) 466-2604",
                       "Premiere destination for Austin’s elite crowd ",
                       "https://litloungeaustin.com/images/page2-img1.jpg",
                       "Saturday, March 4, 2019, 7:00pm - 10:00pm",
                       false, NOW(), NOW(), 5 );
